"""Tests for markdown parser round-trip and edge cases."""

import tempfile
from pathlib import Path

import pytest

from beliefs_lib import Claim
from beliefs_lib.parser import (
    append_claim,
    parse_registry,
    serialize_claim,
    serialize_registry,
    update_claim_status,
)

# -- Fixtures --

MINIMAL_REGISTRY = """\
# Belief Registry
<!-- Generated by beliefs CLI. Hand-editable; run `beliefs check-refs` after manual edits. -->

## Repos
- physics: ~/git/physics

## Claims

### test-claim [IN]
Some claim text
- Source: entries/2026/02/22/test.md
- Source hash: abc123def456
- Date: 2026-02-22
"""

FULL_REGISTRY = """\
# Belief Registry
<!-- Generated by beliefs CLI. Hand-editable; run `beliefs check-refs` after manual edits. -->

## Repos
- physics: ~/git/physics
- verifier: ~/git/physics-verifier

## Claims

### axiom-one [IN] AXIOM
The elastic medium exists
- Source: entries/2026/02/20/axiom.md
- Source hash: aaaa1111
- Date: 2026-02-20

### derived-one [IN] DERIVED
Poisson equation follows from continuum limit
- Source: entries/2026/02/20/poisson.md
- Source hash: bbbb2222
- Date: 2026-02-20
- Assumes: elastic-medium
- Depends on: axiom-one

### stale-one [STALE]
Kerr metric fully derived
- Source: entries/2026/02/19/kerr.md
- Source hash: cccc3333
- Date: 2026-02-19
- Stale reason: Only equatorial plane derived

### retracted-one [OUT]
Five tests are valid
- Source: verifier:entries/2026/02/20/audit.md
- Source hash: dddd4444
- Date: 2026-02-20
- Retracted by: verifier-audit
"""


@pytest.fixture
def tmp_registry(tmp_path):
    """Write MINIMAL_REGISTRY to a temp file and return the path."""
    p = tmp_path / "beliefs.md"
    p.write_text(MINIMAL_REGISTRY)
    return p


@pytest.fixture
def tmp_full_registry(tmp_path):
    """Write FULL_REGISTRY to a temp file and return the path."""
    p = tmp_path / "beliefs.md"
    p.write_text(FULL_REGISTRY)
    return p


# -- parse_registry --


class TestParseRegistry:
    def test_parses_repos(self, tmp_registry):
        repos, claims = parse_registry(tmp_registry)
        assert repos == {"physics": "~/git/physics"}

    def test_parses_single_claim(self, tmp_registry):
        repos, claims = parse_registry(tmp_registry)
        assert len(claims) == 1
        c = claims[0]
        assert c.id == "test-claim"
        assert c.status == "IN"
        assert c.text == "Some claim text"
        assert c.source == "entries/2026/02/22/test.md"
        assert c.source_hash == "abc123def456"
        assert c.date == "2026-02-22"

    def test_parses_multiple_claims(self, tmp_full_registry):
        repos, claims = parse_registry(tmp_full_registry)
        assert len(claims) == 4
        ids = [c.id for c in claims]
        assert ids == ["axiom-one", "derived-one", "stale-one", "retracted-one"]

    def test_parses_repos_multiple(self, tmp_full_registry):
        repos, claims = parse_registry(tmp_full_registry)
        assert repos == {
            "physics": "~/git/physics",
            "verifier": "~/git/physics-verifier",
        }

    def test_parses_claim_type(self, tmp_full_registry):
        repos, claims = parse_registry(tmp_full_registry)
        assert claims[0].type == "AXIOM"
        assert claims[1].type == "DERIVED"
        assert claims[2].type == ""
        assert claims[3].type == ""

    def test_parses_status(self, tmp_full_registry):
        repos, claims = parse_registry(tmp_full_registry)
        statuses = [c.status for c in claims]
        assert statuses == ["IN", "IN", "STALE", "OUT"]

    def test_parses_assumes(self, tmp_full_registry):
        repos, claims = parse_registry(tmp_full_registry)
        assert claims[1].assumes == ["elastic-medium"]

    def test_parses_depends_on(self, tmp_full_registry):
        repos, claims = parse_registry(tmp_full_registry)
        assert claims[1].depends_on == ["axiom-one"]

    def test_parses_stale_reason(self, tmp_full_registry):
        repos, claims = parse_registry(tmp_full_registry)
        assert claims[2].stale_reason == "Only equatorial plane derived"

    def test_parses_retracted_by(self, tmp_full_registry):
        repos, claims = parse_registry(tmp_full_registry)
        assert claims[3].retracted_by == "verifier-audit"

    def test_parses_cross_repo_source(self, tmp_full_registry):
        repos, claims = parse_registry(tmp_full_registry)
        assert claims[3].source == "verifier:entries/2026/02/20/audit.md"


# -- serialize round-trip --


class TestSerializeRoundTrip:
    def test_claim_round_trip(self):
        """serialize_claim → parse back → same fields."""
        original = Claim(
            id="round-trip",
            text="Test round trip",
            source="entries/2026/02/22/test.md",
            source_hash="aabb1122",
            date="2026-02-22",
            status="IN",
            type="DERIVED",
            assumes=["axiom-a", "axiom-b"],
            depends_on=["dep-one"],
        )
        md = serialize_claim(original)
        # Wrap in minimal registry to parse
        registry_text = (
            "# Belief Registry\n"
            "<!-- -->\n\n"
            "## Repos\n"
            "- test: ~/git/test\n\n"
            "## Claims\n\n"
            f"{md}\n"
        )
        with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
            f.write(registry_text)
            tmp = Path(f.name)
        try:
            repos, claims = parse_registry(tmp)
            assert len(claims) == 1
            c = claims[0]
            assert c.id == original.id
            assert c.text == original.text
            assert c.source == original.source
            assert c.source_hash == original.source_hash
            assert c.date == original.date
            assert c.status == original.status
            assert c.type == original.type
            assert c.assumes == original.assumes
            assert c.depends_on == original.depends_on
        finally:
            tmp.unlink()

    def test_full_registry_round_trip(self, tmp_full_registry):
        """parse → serialize → parse → same claims."""
        repos1, claims1 = parse_registry(tmp_full_registry)
        md = serialize_registry(repos1, claims1)
        tmp2 = tmp_full_registry.parent / "beliefs2.md"
        tmp2.write_text(md)
        repos2, claims2 = parse_registry(tmp2)

        assert repos1 == repos2
        assert len(claims1) == len(claims2)
        for c1, c2 in zip(claims1, claims2):
            assert c1.id == c2.id
            assert c1.text == c2.text
            assert c1.status == c2.status
            assert c1.type == c2.type
            assert c1.source == c2.source
            assert c1.date == c2.date
            assert c1.assumes == c2.assumes
            assert c1.depends_on == c2.depends_on


# -- update_claim_status --


class TestUpdateClaimStatus:
    def test_update_status(self, tmp_registry):
        update_claim_status(tmp_registry, "test-claim", "STALE")
        repos, claims = parse_registry(tmp_registry)
        assert claims[0].status == "STALE"

    def test_update_preserves_other_fields(self, tmp_registry):
        update_claim_status(tmp_registry, "test-claim", "STALE")
        repos, claims = parse_registry(tmp_registry)
        c = claims[0]
        assert c.text == "Some claim text"
        assert c.source == "entries/2026/02/22/test.md"
        assert c.source_hash == "abc123def456"
        assert c.date == "2026-02-22"

    def test_update_replaces_source_not_duplicates(self, tmp_registry):
        """The bug: update was appending duplicate Source lines."""
        update_claim_status(
            tmp_registry, "test-claim", "IN",
            source="entries/2026/02/22/new.md",
            source_hash="newwwww999",
        )
        text = tmp_registry.read_text()
        assert text.count("- Source:") == 1
        assert text.count("- Source Hash:") == 1
        assert "new.md" in text
        assert "abc123def456" not in text

    def test_update_replaces_source_parses_correctly(self, tmp_registry):
        """After replacing source, re-parse gives the new value."""
        update_claim_status(
            tmp_registry, "test-claim", "IN",
            source="entries/2026/02/22/new.md",
            source_hash="newwwww999",
        )
        repos, claims = parse_registry(tmp_registry)
        assert claims[0].source == "entries/2026/02/22/new.md"
        assert claims[0].source_hash == "newwwww999"

    def test_update_adds_new_metadata(self, tmp_registry):
        """New fields that don't exist yet should be appended."""
        update_claim_status(
            tmp_registry, "test-claim", "STALE",
            stale_reason="Source file changed",
        )
        repos, claims = parse_registry(tmp_registry)
        assert claims[0].stale_reason == "Source file changed"

    def test_update_replaces_stale_reason(self, tmp_registry):
        """Updating stale_reason twice should replace, not duplicate."""
        update_claim_status(
            tmp_registry, "test-claim", "STALE",
            stale_reason="First reason",
        )
        update_claim_status(
            tmp_registry, "test-claim", "STALE",
            stale_reason="Second reason",
        )
        text = tmp_registry.read_text()
        assert text.count("Stale Reason:") == 1
        assert "Second reason" in text
        assert "First reason" not in text

    def test_update_preserves_type(self, tmp_full_registry):
        update_claim_status(tmp_full_registry, "axiom-one", "STALE")
        repos, claims = parse_registry(tmp_full_registry)
        axiom = [c for c in claims if c.id == "axiom-one"][0]
        assert axiom.type == "AXIOM"
        assert axiom.status == "STALE"

    def test_update_does_not_affect_other_claims(self, tmp_full_registry):
        update_claim_status(tmp_full_registry, "axiom-one", "OUT")
        repos, claims = parse_registry(tmp_full_registry)
        assert len(claims) == 4
        assert claims[1].id == "derived-one"
        assert claims[1].status == "IN"
        assert claims[2].id == "stale-one"
        assert claims[2].status == "STALE"


# -- append_claim --


class TestAppendClaim:
    def test_append_adds_claim(self, tmp_registry):
        new = Claim(
            id="new-claim",
            text="A new belief",
            source="entries/2026/02/22/new.md",
            source_hash="ffff0000",
            date="2026-02-22",
            status="IN",
        )
        append_claim(tmp_registry, new)
        repos, claims = parse_registry(tmp_registry)
        assert len(claims) == 2
        assert claims[1].id == "new-claim"
        assert claims[1].text == "A new belief"

    def test_append_preserves_existing(self, tmp_registry):
        new = Claim(id="new-claim", text="New", status="IN")
        append_claim(tmp_registry, new)
        repos, claims = parse_registry(tmp_registry)
        assert claims[0].id == "test-claim"
        assert claims[0].source == "entries/2026/02/22/test.md"


# -- Edge cases for markdown fragility --


class TestMarkdownEdgeCases:
    def test_claim_text_with_markdown_formatting(self, tmp_path):
        """Claim text containing markdown (bold, backticks) parses correctly."""
        md = (
            "# Belief Registry\n<!-- -->\n\n"
            "## Repos\n- test: ~/git/test\n\n"
            "## Claims\n\n"
            "### fmt-claim [IN]\n"
            "The **acoustic metric** gives `g_tt = -(c^2 - v^2)`\n"
            "- Source: test.md\n"
            "- Date: 2026-02-22\n"
        )
        p = tmp_path / "beliefs.md"
        p.write_text(md)
        repos, claims = parse_registry(p)
        assert claims[0].text == "The **acoustic metric** gives `g_tt = -(c^2 - v^2)`"

    def test_claim_text_starting_with_dash(self, tmp_path):
        """Claim text that starts with '- ' could be confused with metadata."""
        md = (
            "# Belief Registry\n<!-- -->\n\n"
            "## Repos\n- test: ~/git/test\n\n"
            "## Claims\n\n"
            "### dash-claim [IN]\n"
            "Gravity is emergent from elastic dynamics\n"
            "- Source: test.md\n"
            "- Date: 2026-02-22\n"
        )
        p = tmp_path / "beliefs.md"
        p.write_text(md)
        repos, claims = parse_registry(p)
        assert claims[0].id == "dash-claim"
        assert claims[0].source == "test.md"

    def test_empty_claims_section(self, tmp_path):
        md = (
            "# Belief Registry\n<!-- -->\n\n"
            "## Repos\n- test: ~/git/test\n\n"
            "## Claims\n\n"
        )
        p = tmp_path / "beliefs.md"
        p.write_text(md)
        repos, claims = parse_registry(p)
        assert claims == []
        assert repos == {"test": "~/git/test"}

    def test_multiple_assumes(self, tmp_path):
        """Comma-separated assumes parse into list."""
        md = (
            "# Belief Registry\n<!-- -->\n\n"
            "## Repos\n- test: ~/git/test\n\n"
            "## Claims\n\n"
            "### multi-assume [IN]\n"
            "Depends on many things\n"
            "- Assumes: axiom-a, axiom-b, axiom-c\n"
            "- Date: 2026-02-22\n"
        )
        p = tmp_path / "beliefs.md"
        p.write_text(md)
        repos, claims = parse_registry(p)
        assert claims[0].assumes == ["axiom-a", "axiom-b", "axiom-c"]

    def test_source_hash_case_insensitive_key(self, tmp_path):
        """'Source hash' and 'Source Hash' should both parse."""
        for key in ["Source hash", "Source Hash"]:
            md = (
                "# Belief Registry\n<!-- -->\n\n"
                "## Repos\n- test: ~/git/test\n\n"
                "## Claims\n\n"
                f"### hash-case [IN]\nTest\n- {key}: aabb1122\n"
            )
            p = tmp_path / "beliefs.md"
            p.write_text(md)
            repos, claims = parse_registry(p)
            assert claims[0].source_hash == "aabb1122", f"Failed for key '{key}'"

    def test_trailing_whitespace_in_source(self, tmp_path):
        """Source paths with trailing whitespace should be stripped."""
        md = (
            "# Belief Registry\n<!-- -->\n\n"
            "## Repos\n- test: ~/git/test\n\n"
            "## Claims\n\n"
            "### ws-claim [IN]\nTest\n"
            "- Source: entries/2026/02/22/test.md   \n"
            "- Date: 2026-02-22\n"
        )
        p = tmp_path / "beliefs.md"
        p.write_text(md)
        repos, claims = parse_registry(p)
        assert claims[0].source == "entries/2026/02/22/test.md"

    def test_no_blank_line_between_claims(self, tmp_path):
        """Claims without blank line separator should still parse."""
        md = (
            "# Belief Registry\n<!-- -->\n\n"
            "## Repos\n- test: ~/git/test\n\n"
            "## Claims\n\n"
            "### claim-a [IN]\nFirst claim\n- Date: 2026-02-22\n"
            "### claim-b [IN]\nSecond claim\n- Date: 2026-02-22\n"
        )
        p = tmp_path / "beliefs.md"
        p.write_text(md)
        repos, claims = parse_registry(p)
        assert len(claims) == 2
        assert claims[0].id == "claim-a"
        assert claims[1].id == "claim-b"
