"""Tests for read-only mode when beliefs.md is generated by reasons."""

import tempfile
from pathlib import Path

import pytest

from beliefs_lib.parser import is_generated

GENERATED_HEADER = """\
# Belief Registry
<!-- Generated by reasons export-markdown. Do not edit — operate through reasons. -->

## Claims

### test-claim [IN] OBSERVATION
Some claim text
- Source: entries/test.md
- Date: 2026-03-23
"""

HAND_EDITED_HEADER = """\
# Belief Registry
<!-- Generated by beliefs CLI. Hand-editable; run `beliefs check-refs` after manual edits. -->

## Repos

## Claims

### test-claim [IN]
Some claim text
- Source: entries/test.md
- Date: 2026-03-23
"""


class TestIsGenerated:
    def test_detects_generated_file(self, tmp_path):
        f = tmp_path / "beliefs.md"
        f.write_text(GENERATED_HEADER)
        assert is_generated(f) is True

    def test_hand_edited_not_generated(self, tmp_path):
        f = tmp_path / "beliefs.md"
        f.write_text(HAND_EDITED_HEADER)
        assert is_generated(f) is False

    def test_missing_file_not_generated(self, tmp_path):
        f = tmp_path / "missing.md"
        assert is_generated(f) is False

    def test_empty_file_not_generated(self, tmp_path):
        f = tmp_path / "beliefs.md"
        f.write_text("")
        assert is_generated(f) is False


class TestReadOnlyGuard:
    """Write commands should fail on generated files."""

    @pytest.fixture
    def generated_registry(self, tmp_path):
        f = tmp_path / "beliefs.md"
        f.write_text(GENERATED_HEADER)
        return f

    @pytest.fixture
    def editable_registry(self, tmp_path):
        f = tmp_path / "beliefs.md"
        f.write_text(HAND_EDITED_HEADER)
        # Also need nogoods.md for some commands
        (tmp_path / "nogoods.md").write_text("# Nogoods\n\n")
        return f

    def _run_cli(self, args):
        """Run beliefs CLI with args, return exit code."""
        import subprocess
        result = subprocess.run(
            ["uv", "run", "beliefs"] + args,
            capture_output=True, text=True,
            cwd=str(Path(__file__).parent.parent),
        )
        return result

    def test_add_blocked_on_generated(self, generated_registry):
        r = self._run_cli([
            "--registry", str(generated_registry),
            "add", "--id", "new-claim", "--text", "test",
        ])
        assert r.returncode == 1
        assert "and is read-only" in r.stderr

    def test_add_allowed_on_editable(self, editable_registry):
        r = self._run_cli([
            "--registry", str(editable_registry),
            "add", "--id", "new-claim", "--text", "test",
        ])
        assert r.returncode == 0

    def test_update_blocked_on_generated(self, generated_registry):
        r = self._run_cli([
            "--registry", str(generated_registry),
            "update", "test-claim", "--status", "OUT",
        ])
        assert r.returncode == 1
        assert "and is read-only" in r.stderr

    def test_list_allowed_on_generated(self, generated_registry):
        r = self._run_cli([
            "--registry", str(generated_registry),
            "list",
        ])
        assert r.returncode == 0
        assert "test-claim" in r.stdout

    def test_show_allowed_on_generated(self, generated_registry):
        r = self._run_cli([
            "--registry", str(generated_registry),
            "show", "test-claim",
        ])
        assert r.returncode == 0
        assert "test-claim" in r.stdout

    def test_check_stale_allowed_on_generated(self, generated_registry):
        r = self._run_cli([
            "--registry", str(generated_registry),
            "check-stale",
        ])
        # May exit 0 or 1 depending on staleness, but should not be blocked
        assert "is read-only (generated by reasons)" not in r.stderr

    def test_hash_sources_blocked_on_generated(self, generated_registry):
        r = self._run_cli([
            "--registry", str(generated_registry),
            "hash-sources",
        ])
        assert r.returncode == 1
        assert "and is read-only" in r.stderr
