"""Markdown parse/serialize for beliefs.md and nogoods.md."""

import re
from pathlib import Path

from . import Claim, Nogood

HEADER_RE = re.compile(r'^### ([\w-]+) \[(IN|OUT|STALE)\](?:[ \t]+(\w+))?')
META_RE = re.compile(r'^- ([\w][\w\s]*\w|[\w]): (.+)')
REPO_RE = re.compile(r'^- ([\w-]+): (.+)')
NOGOOD_HEADER_RE = re.compile(r'^### (nogood-\d+): (.+)')
GENERATED_MARKER = "Generated by reasons"


def is_generated(path: Path) -> bool:
    """Check if a beliefs.md was generated by reasons export-markdown."""
    try:
        # Only need to check the first few lines for the marker comment
        with open(path) as f:
            for _ in range(5):
                line = f.readline()
                if not line:
                    break
                if GENERATED_MARKER in line:
                    return True
    except (OSError, FileNotFoundError):
        pass
    return False


def parse_registry(path: Path) -> tuple[dict[str, str], list[Claim]]:
    """Parse beliefs.md into (repos_dict, claims_list)."""
    text = path.read_text()
    repos = {}
    claims = []

    # Parse repos section
    in_repos = False
    for line in text.splitlines():
        if line.strip() == "## Repos":
            in_repos = True
            continue
        if in_repos:
            if line.startswith("## "):
                break
            m = REPO_RE.match(line)
            if m:
                repos[m.group(1)] = m.group(2).strip()

    # Parse claims — split on ### headers
    sections = re.split(r'^(?=### )', text, flags=re.MULTILINE)
    for section in sections:
        m = HEADER_RE.match(section)
        if not m:
            continue
        claim = Claim(id=m.group(1), text="", status=m.group(2))
        if m.group(3):
            claim.type = m.group(3)

        lines = section.splitlines()[1:]  # skip header
        text_found = False
        for line in lines:
            mm = META_RE.match(line)
            if mm:
                key = mm.group(1).strip().lower()
                val = mm.group(2).strip()
                if key == "source":
                    claim.source = val
                elif key == "source hash":
                    claim.source_hash = val
                elif key == "date":
                    claim.date = val
                elif key == "assumes":
                    claim.assumes = [a.strip() for a in val.split(",")]
                elif key == "depends on":
                    claim.depends_on = [d.strip() for d in val.split(",")]
                elif key == "retracted by":
                    claim.retracted_by = val
                elif key == "nogood":
                    claim.nogood = val
                elif key == "stale reason":
                    claim.stale_reason = val
                elif key == "superseded by":
                    claim.superseded_by = val
                elif key == "ref check":
                    claim.ref_check = val
            elif line.strip() and not text_found:
                claim.text = line.strip()
                text_found = True

        claims.append(claim)

    return repos, claims


def serialize_claim(claim: Claim) -> str:
    """Serialize a single claim to markdown."""
    header = f"### {claim.id} [{claim.status}]"
    if claim.type:
        header += f" {claim.type}"
    lines = [header, claim.text]

    if claim.source:
        lines.append(f"- Source: {claim.source}")
    if claim.source_hash:
        lines.append(f"- Source hash: {claim.source_hash}")
    if claim.date:
        lines.append(f"- Date: {claim.date}")
    if claim.assumes:
        lines.append(f"- Assumes: {', '.join(claim.assumes)}")
    if claim.depends_on:
        lines.append(f"- Depends on: {', '.join(claim.depends_on)}")
    if claim.retracted_by:
        lines.append(f"- Retracted by: {claim.retracted_by}")
    if claim.nogood:
        lines.append(f"- Nogood: {claim.nogood}")
    if claim.stale_reason:
        lines.append(f"- Stale reason: {claim.stale_reason}")
    if claim.superseded_by:
        lines.append(f"- Superseded by: {claim.superseded_by}")
    if claim.ref_check:
        lines.append(f"- Ref check: {claim.ref_check}")

    return "\n".join(lines)


def serialize_registry(repos: dict[str, str], claims: list[Claim]) -> str:
    """Serialize full registry to markdown."""
    lines = [
        "# Belief Registry",
        "<!-- Generated by beliefs CLI. Hand-editable; run `beliefs check-refs` after manual edits. -->",
        "",
        "## Repos",
    ]
    for name, path in sorted(repos.items()):
        lines.append(f"- {name}: {path}")
    lines.append("")
    lines.append("## Claims")
    lines.append("")

    for claim in claims:
        lines.append(serialize_claim(claim))
        lines.append("")

    return "\n".join(lines)


def append_claim(path: Path, claim: Claim) -> None:
    """Append one claim section to beliefs.md."""
    text = path.read_text()
    if not text.endswith("\n"):
        text += "\n"
    text += "\n" + serialize_claim(claim) + "\n"
    path.write_text(text)


def update_claim_status(path: Path, claim_id: str, new_status: str, **extra) -> None:
    """Rewrite a claim's status in-place and add extra metadata lines."""
    text = path.read_text()
    lines = text.splitlines()
    result = []
    i = 0

    while i < len(lines):
        m = HEADER_RE.match(lines[i])
        if m and m.group(1) == claim_id:
            # Rewrite header with new status
            old_type = m.group(3) or ""
            new_header = f"### {claim_id} [{new_status}]"
            if old_type:
                new_header += f" {old_type}"
            result.append(new_header)
            i += 1

            # Copy existing claim body until next header
            body_lines = []
            while i < len(lines) and not HEADER_RE.match(lines[i]):
                body_lines.append(lines[i])
                i += 1

            # Strip trailing blank lines so extra metadata stays attached
            trailing = []
            while body_lines and not body_lines[-1].strip():
                trailing.append(body_lines.pop())

            # Replace existing metadata lines if extra provides new values
            extra_keys_used = set()
            text_replaced = False
            new_text = extra.pop("text", None)
            for line in body_lines:
                mm = META_RE.match(line)
                if mm:
                    existing_key = mm.group(1).strip().lower().replace(" ", "_")
                    if existing_key in extra:
                        display_key = existing_key.replace("_", " ").title()
                        result.append(f"- {display_key}: {extra[existing_key]}")
                        extra_keys_used.add(existing_key)
                        continue
                elif new_text and not text_replaced and line.strip() and not line.startswith("- "):
                    result.append(new_text)
                    text_replaced = True
                    continue
                result.append(line)

            # Append any extra metadata that didn't replace an existing line
            for key, val in extra.items():
                if key not in extra_keys_used:
                    display_key = key.replace("_", " ").title()
                    result.append(f"- {display_key}: {val}")

            # Restore trailing blank lines
            result.extend(trailing)
        else:
            result.append(lines[i])
            i += 1

    path.write_text("\n".join(result) + "\n")


def parse_nogoods(path: Path) -> list[Nogood]:
    """Parse nogoods.md into list of Nogood."""
    text = path.read_text()
    nogoods = []

    sections = re.split(r'^(?=### )', text, flags=re.MULTILINE)
    for section in sections:
        m = NOGOOD_HEADER_RE.match(section)
        if not m:
            continue
        nogood = Nogood(id=m.group(1), description=m.group(2).strip())

        for line in section.splitlines()[1:]:
            mm = META_RE.match(line)
            if mm:
                key = mm.group(1).strip().lower()
                val = mm.group(2).strip()
                if key == "discovered":
                    nogood.discovered = val
                elif key == "discovered by":
                    nogood.discovered_by = val
                elif key == "resolution":
                    nogood.resolution = val
                elif key == "affects":
                    nogood.affects = [a.strip() for a in val.split(",")]

        nogoods.append(nogood)

    return nogoods


def append_nogood(path: Path, nogood: Nogood) -> None:
    """Append one nogood section to nogoods.md."""
    text = path.read_text()
    if not text.endswith("\n"):
        text += "\n"
    lines = [f"\n### {nogood.id}: {nogood.description}"]
    if nogood.discovered:
        lines.append(f"- Discovered: {nogood.discovered}")
    if nogood.discovered_by:
        lines.append(f"- Discovered by: {nogood.discovered_by}")
    if nogood.resolution:
        lines.append(f"- Resolution: {nogood.resolution}")
    if nogood.affects:
        lines.append(f"- Affects: {', '.join(nogood.affects)}")
    text += "\n".join(lines) + "\n"
    path.write_text(text)
